### ISSUE TITLE
Required feature missing

### ISSUE THREAD

**Issue by codepathreview** [abhishekagrawal1/moviecatch#1]
@abhishekagrawal1 from your code, it seems you haven't implemented [ViewHolder](http://guides.codepath.com/android/Using-an-ArrayAdapter-with-ListView#improving-performance-with-the-viewholder-pattern) pattern, even though you have checked it to be complete in README. It is a required feature.

It is important you complete all required features. Please implement the ViewHolder pattern and resubmit.

**Comment by abhishekagrawal1** [comment]
Hi, I have corrected the ViewHolder Pattern implementation and pushed the code git. Kindly let me know if you still issues exists in the implementation.
